//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLife.Store.Resources
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class EmailTemplates
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal EmailTemplates()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InLife.Store.Resources.EmailTemplates", typeof(EmailTemplates).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///	&lt;head&gt;
		///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///		&lt;title&gt;InLife Store&lt;/Title&gt;
		///	&lt;/head&gt;
		///	&lt;body&gt;
		///		&lt;p style=&quot;font-family:&apos;sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			An error has occurred.
		///		&lt;/p&gt;
		///		&lt;p style=&quot;font-family:&apos;sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			#MESSAGE#
		///		&lt;/p&gt;
		///	&lt;/body&gt;
		///&lt;/html&gt;
		///.
		/// </summary>
		public static string ErrorNotification
		{
			get
			{
				return ResourceManager.GetString("ErrorNotification", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///&lt;head&gt;
		///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///    &lt;title&gt;InLife Store Group Application Cancel - #REFERENCE-CODE#&lt;/title&gt;
		///    &lt;style&gt;
		///        table, th, td {
		///            border: 1px solid black;
		///            border-collapse: collapse;
		///        }
		///
		///        th, td {
		///            padding: 5px;
		///            text-align: left;
		///        }
		///    &lt;/style&gt;
		///&lt;/head&gt;
		///&lt;body&gt;
		///    &lt;div style=&quot;margin:0 auto; max-width:600px; background:#fff;&quot;&gt;
		///        &lt;div [rest of string was truncated]&quot;;.
		/// </summary>
		public static string GroupApplicationCancel
		{
			get
			{
				return ResourceManager.GetString("GroupApplicationCancel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///&lt;head&gt;
		///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///	&lt;title&gt;InLife Store Group Application Complete - #REFERENCE-CODE#&lt;/title&gt;
		///&lt;/head&gt;
		///&lt;body&gt;
		///	&lt;div style=&quot;margin:0 auto; max-width:600px; background:#fff;&quot;&gt;
		///		&lt;div style=&quot;background:#e43e25; padding:20px; color:#fff;&quot;&gt;
		///			&lt;h1 style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; font-weight:300; text-align:center;&quot;&gt;Group Insurance Complete&lt;/h1&gt;
		///		&lt;/div&gt;
		///		&lt;div style=&quot;padding [rest of string was truncated]&quot;;.
		/// </summary>
		public static string GroupApplicationCompleteAdmin
		{
			get
			{
				return ResourceManager.GetString("GroupApplicationCompleteAdmin", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///&lt;head&gt;
		///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///	&lt;title&gt;InLife Store Group Application Feedback - #REFERENCE-CODE#&lt;/title&gt;
		///&lt;/head&gt;
		///&lt;body&gt;
		///	&lt;div style=&quot;margin:0 auto; max-width:600px; background:#fff;&quot;&gt;
		///		&lt;div style=&quot;background:#e43e25; padding:20px; color:#fff;&quot;&gt;
		///			&lt;h1 style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; font-weight:300; text-align:center;&quot;&gt;Group Insurance Feedback&lt;/h1&gt;
		///		&lt;/div&gt;
		///		&lt;div style=&quot;padding [rest of string was truncated]&quot;;.
		/// </summary>
		public static string GroupApplicationFeedbackAdmin
		{
			get
			{
				return ResourceManager.GetString("GroupApplicationFeedbackAdmin", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///&lt;head&gt;
		///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///	&lt;title&gt;InLife Store One-Time Password&lt;/title&gt;
		///&lt;/head&gt;
		///&lt;body&gt;
		///	&lt;div style=&quot;margin:0 auto; max-width:600px; background:#fff;&quot;&gt;
		///		&lt;div style=&quot;background:#e43e25; padding:20px; color:#fff;&quot;&gt;
		///			&lt;h1 style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; font-weight:300; text-align:center;&quot;&gt;Group Insurance OTP&lt;/h1&gt;
		///		&lt;/div&gt;
		///		&lt;div style=&quot;padding:20px 0;&quot;&gt;
		///			&lt;p style=&quot;font-fam [rest of string was truncated]&quot;;.
		/// </summary>
		public static string GroupApplicationOtp
		{
			get
			{
				return ResourceManager.GetString("GroupApplicationOtp", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///&lt;head&gt;
		///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///    &lt;title&gt;InLife Store Group Application Proof of Payment - #REFERENCE-CODE#&lt;/title&gt;
		///
		///    &lt;style&gt;
		///        table, th, td {
		///            border: 1px solid black;
		///            border-collapse: collapse;
		///        }
		///
		///        th, td {
		///            padding: 5px;
		///            text-align: left;
		///        }
		///    &lt;/style&gt;
		///&lt;/head&gt;
		///&lt;body&gt;
		///    &lt;div style=&quot;margin:0 auto; max-width:600px; background:#fff;&quot;&gt;
		/// [rest of string was truncated]&quot;;.
		/// </summary>
		public static string GroupApplicationPaymentProof
		{
			get
			{
				return ResourceManager.GetString("GroupApplicationPaymentProof", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///&lt;head&gt;
		///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///	&lt;title&gt;InLife Store&lt;/title&gt;
		///&lt;/head&gt;
		///&lt;body&gt;
		///	&lt;div style=&quot;margin:0 auto; max-width:600px; background:#fff;&quot;&gt;
		///		&lt;div style=&quot;background:#3951a2; padding:20px; color:#fff;&quot;&gt;
		///			&lt;h1 style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; font-weight:300; text-align:center;&quot;&gt;Group Insurance Reference Code&lt;/h1&gt;
		///		&lt;/div&gt;
		///		&lt;div style=&quot;padding:20px 0;&quot;&gt;
		///			&lt;p style=&quot;font-family:san [rest of string was truncated]&quot;;.
		/// </summary>
		public static string GroupApplicationReferenceCode
		{
			get
			{
				return ResourceManager.GetString("GroupApplicationReferenceCode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///&lt;head&gt;
		///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///	&lt;title&gt;InLife Store Group Applications&lt;/title&gt;
		///&lt;/head&gt;
		///&lt;body&gt;
		///	&lt;div style=&quot;margin:0 auto; background:#fff;&quot;&gt;
		///		&lt;h1 style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; font-weight:300;&quot;&gt;Group Insurance Applications&lt;/h1&gt;
		///		&lt;div style=&quot;padding:20px 0; font-family:sans-serif; font-size:1em; line-height:1.5em;&quot;&gt;
		///
		///			&lt;p&gt;
		///				Hi, &lt;br /&gt;
		///				Please see the list below of subm [rest of string was truncated]&quot;;.
		/// </summary>
		public static string GroupApplicationsCompletedBatch
		{
			get
			{
				return ResourceManager.GetString("GroupApplicationsCompletedBatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///&lt;head&gt;
		///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///	&lt;title&gt;InLife Store Group Application&lt;/title&gt;
		///&lt;/head&gt;
		///&lt;body&gt;
		///	&lt;div style=&quot;margin:0 auto; max-width:600px; background:#fff;&quot;&gt;
		///		&lt;div style=&quot;background:#e43e25; padding:20px; color:#fff;&quot;&gt;
		///			&lt;h1 style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; font-weight:300; text-align:center;&quot;&gt;Group Insurance&lt;/h1&gt;
		///		&lt;/div&gt;
		///		&lt;div style=&quot;padding:20px 0; font-family:sans-serif; font [rest of string was truncated]&quot;;.
		/// </summary>
		public static string GroupApplicationThankYou
		{
			get
			{
				return ResourceManager.GetString("GroupApplicationThankYou", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///	&lt;head&gt;
		///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///		&lt;title&gt;InLife Store&lt;/Title&gt;
		///	&lt;/head&gt;
		///	&lt;body&gt;
		///		&lt;p style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			Hi #NAME#,
		///		&lt;/p&gt;
		///		&lt;p style=&quot;font-family:sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ac consequat orci. Vestibulum tristique aliquam libero a [rest of string was truncated]&quot;;.
		/// </summary>
		public static string OrderConfirmation
		{
			get
			{
				return ResourceManager.GetString("OrderConfirmation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///	&lt;head&gt;
		///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///		&lt;title&gt;InLife Store&lt;/title&gt;
		///	&lt;/head&gt;
		///	&lt;body&gt;
		///		&lt;p style=&quot;font-family:sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			A new order request has been sent
		///		&lt;/p&gt;
		///		&lt;p style=&quot;font-family:sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			&lt;span&gt;Name:&lt;/span&gt;
		///			&lt;strong&gt;#NAME#&lt;/strong&gt;
		///		&lt;/p&gt;
		///		&lt;p style=&quot;font-family:sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			&lt;span&gt;Email:&lt;/sp [rest of string was truncated]&quot;;.
		/// </summary>
		public static string OrderConfirmationAdmin
		{
			get
			{
				return ResourceManager.GetString("OrderConfirmationAdmin", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///	&lt;head&gt;
		///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///		&lt;title&gt;InLife Store&lt;/Title&gt;
		///	&lt;/head&gt;
		///	&lt;body&gt;
		///		&lt;p style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			Hi #NAME#,
		///		&lt;/p&gt;
		///		&lt;p style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ac consequat orci [rest of string was truncated]&quot;;.
		/// </summary>
		public static string PaymentReminder
		{
			get
			{
				return ResourceManager.GetString("PaymentReminder", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///	&lt;head&gt;
		///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///		&lt;title&gt;InLife Store&lt;/title&gt;
		///	&lt;/head&gt;
		///	&lt;body&gt;
		///		&lt;p style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			Payment reminder
		///		&lt;/p&gt;
		///		&lt;p style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			&lt;span&gt;Name:&lt;/span&gt;
		///			&lt;strong&gt;#NAME#&lt;/strong&gt;
		///		&lt;/p&gt;
		///		&lt;p style=&quot;font-family:&apos;Rob [rest of string was truncated]&quot;;.
		/// </summary>
		public static string PaymentReminderAdmin
		{
			get
			{
				return ResourceManager.GetString("PaymentReminderAdmin", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///	&lt;head&gt;
		///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///		&lt;title&gt;InLife Store&lt;/Title&gt;
		///	&lt;/head&gt;
		///	&lt;body&gt;
		///		&lt;p style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			Hi #NAME#,
		///		&lt;/p&gt;
		///		&lt;p style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ac consequat orci [rest of string was truncated]&quot;;.
		/// </summary>
		public static string QuoteRequest
		{
			get
			{
				return ResourceManager.GetString("QuoteRequest", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
		///&lt;html&gt;
		///	&lt;head&gt;
		///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///		&lt;title&gt;InLife Store&lt;/title&gt;
		///	&lt;/head&gt;
		///	&lt;body&gt;
		///		&lt;p style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			A new order request has been sent
		///		&lt;/p&gt;
		///		&lt;p style=&quot;font-family:&apos;Roboto&apos;, &apos;Helvetica Neue&apos;, &apos;Segoe&apos;, &apos;Segoe UI&apos;, sans-serif; line-height:1.5em; margin-bottom:1em;&quot;&gt;
		///			&lt;span&gt;Name:&lt;/span&gt;
		///			&lt;strong&gt;#NAME#&lt;/strong&gt;
		///		&lt;/p&gt;
		///		&lt;p style= [rest of string was truncated]&quot;;.
		/// </summary>
		public static string QuoteRequestAdmin
		{
			get
			{
				return ResourceManager.GetString("QuoteRequestAdmin", resourceCulture);
			}
		}
	}
}
