//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLife.Store.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReferenceTables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceTables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InLife.Store.Resources.ReferenceTables", typeof(ReferenceTables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{ &quot;id&quot;: &quot;1&quot;, &quot;name&quot;: &quot;Annulled&quot; },
        ///	{ &quot;id&quot;: &quot;2&quot;, &quot;name&quot;: &quot;Divorced&quot; },
        ///	{ &quot;id&quot;: &quot;3&quot;, &quot;name&quot;: &quot;Legally Separated&quot; },
        ///	{ &quot;id&quot;: &quot;4&quot;, &quot;name&quot;: &quot;Married&quot; },
        ///	{ &quot;id&quot;: &quot;5&quot;, &quot;name&quot;: &quot;Single&quot; },
        ///	{ &quot;id&quot;: &quot;6&quot;, &quot;name&quot;: &quot;Widowed&quot; },
        ///	{ &quot;id&quot;: &quot;48&quot;, &quot;name&quot;: &quot;Not Applicable&quot; }
        ///]
        ///.
        /// </summary>
        public static string CivilStatus {
            get {
                return ResourceManager.GetString("CivilStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{ &quot;id&quot;: &quot;1&quot;, &quot;name&quot;: &quot;United States&quot; },
        ///	{ &quot;id&quot;: &quot;2&quot;, &quot;name&quot;: &quot;Canada&quot; },
        ///	{ &quot;id&quot;: &quot;3&quot;, &quot;name&quot;: &quot;Afghanistan&quot; },
        ///	{ &quot;id&quot;: &quot;4&quot;, &quot;name&quot;: &quot;Albania&quot; },
        ///	{ &quot;id&quot;: &quot;5&quot;, &quot;name&quot;: &quot;Algeria&quot; },
        ///	{ &quot;id&quot;: &quot;6&quot;, &quot;name&quot;: &quot;American Samoa&quot; },
        ///	{ &quot;id&quot;: &quot;7&quot;, &quot;name&quot;: &quot;Andorra&quot; },
        ///	{ &quot;id&quot;: &quot;8&quot;, &quot;name&quot;: &quot;Angola&quot; },
        ///	{ &quot;id&quot;: &quot;9&quot;, &quot;name&quot;: &quot;Anguilla&quot; },
        ///	{ &quot;id&quot;: &quot;10&quot;, &quot;name&quot;: &quot;Antarctica&quot; },
        ///	{ &quot;id&quot;: &quot;11&quot;, &quot;name&quot;: &quot;Antigua &amp; Barbuda&quot; },
        ///	{ &quot;id&quot;: &quot;12&quot;, &quot;name&quot;: &quot;Argentina&quot; },
        ///	{ &quot;id&quot;: &quot;13&quot;, &quot;name&quot;: &quot;Armenia&q....
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{ &quot;id&quot;: &quot;284&quot;, &quot;name&quot;: &quot;Business Income&quot; },
        ///	{ &quot;id&quot;: &quot;132&quot;, &quot;name&quot;: &quot;Family Income&quot; },
        ///	{ &quot;id&quot;: &quot;133&quot;, &quot;name&quot;: &quot;Income from Employment&quot; },
        ///	{ &quot;id&quot;: &quot;134&quot;, &quot;name&quot;: &quot;Savings&quot; },
        ///	{ &quot;id&quot;: &quot;210&quot;, &quot;name&quot;: &quot;Rental Income&quot; },
        ///	{ &quot;id&quot;: &quot;212&quot;, &quot;name&quot;: &quot;Interest Income&quot; },
        ///	{ &quot;id&quot;: &quot;213&quot;, &quot;name&quot;: &quot;Investment&quot; },
        ///	{ &quot;id&quot;: &quot;214&quot;, &quot;name&quot;: &quot;Remittance&quot; },
        ///	{ &quot;id&quot;: &quot;215&quot;, &quot;name&quot;: &quot;Pension&quot; }
        ///]
        ///.
        /// </summary>
        public static string FundSource {
            get {
                return ResourceManager.GetString("FundSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{ &quot;id&quot;: &quot;7&quot;, &quot;name&quot;: &quot;Female&quot; },
        ///	{ &quot;id&quot;: &quot;8&quot;, &quot;name&quot;: &quot;Male&quot; }
        ///]
        ///.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{ &quot;id&quot;: &quot;1&quot;, &quot;name&quot;: &quot;PASSPORT&quot; },
        ///	{ &quot;id&quot;: &quot;2&quot;, &quot;name&quot;: &quot;DRIVERâ€™S LICENSE&quot; },
        ///	{ &quot;id&quot;: &quot;3&quot;, &quot;name&quot;: &quot;UNIFIED MULTIPURPOSE ID (UMID)&quot; },
        ///	{ &quot;id&quot;: &quot;4&quot;, &quot;name&quot;: &quot;PROFESSIONAL REGULATION COMMISSION (PRC) ID&quot; },
        ///	{ &quot;id&quot;: &quot;5&quot;, &quot;name&quot;: &quot;VOTERâ€™S OR COMELEC ID CARD&quot; },
        ///	{ &quot;id&quot;: &quot;6&quot;, &quot;name&quot;: &quot;SOCIAL SECURITY SYSTEM (SSS) ID&quot; },
        ///	{ &quot;id&quot;: &quot;7&quot;, &quot;name&quot;: &quot;TAX IDENTIFICATION NUMBER (TIN) CARD&quot; },
        ///	{ &quot;id&quot;: &quot;8&quot;, &quot;name&quot;: &quot;ALIEN CERTIFICATE OF REGISTRATION (ACR) OR IMMIGRANT CERTIFICATE OF REGISTRATION&quot; },
        ///	{  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IdentificationDocumentType {
            get {
                return ResourceManager.GetString("IdentificationDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{ &quot;id&quot;: &quot;19&quot;, &quot;name&quot;: &quot;ATTY&quot; },
        ///	{ &quot;id&quot;: &quot;20&quot;, &quot;name&quot;: &quot;DR&quot; },
        ///	{ &quot;id&quot;: &quot;21&quot;, &quot;name&quot;: &quot;DRA&quot; },
        ///	{ &quot;id&quot;: &quot;22&quot;, &quot;name&quot;: &quot;ENGR&quot; },
        ///	{ &quot;id&quot;: &quot;23&quot;, &quot;name&quot;: &quot;HON&quot; },
        ///	{ &quot;id&quot;: &quot;24&quot;, &quot;name&quot;: &quot;MR&quot; },
        ///	{ &quot;id&quot;: &quot;25&quot;, &quot;name&quot;: &quot;MRS&quot; },
        ///	{ &quot;id&quot;: &quot;26&quot;, &quot;name&quot;: &quot;MS&quot; },
        ///	{ &quot;id&quot;: &quot;27&quot;, &quot;name&quot;: &quot;MSGR&quot; },
        ///	{ &quot;id&quot;: &quot;28&quot;, &quot;name&quot;: &quot;REV&quot; }
        ///]
        ///.
        /// </summary>
        public static string NamePrefix {
            get {
                return ResourceManager.GetString("NamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{ &quot;id&quot;: &quot;1&quot;, &quot;name&quot;: &quot;Not Applicable&quot; },
        ///	{ &quot;id&quot;: &quot;10&quot;, &quot;name&quot;: &quot;II&quot; },
        ///	{ &quot;id&quot;: &quot;11&quot;, &quot;name&quot;: &quot;III&quot; },
        ///	{ &quot;id&quot;: &quot;12&quot;, &quot;name&quot;: &quot;IV&quot; },
        ///	{ &quot;id&quot;: &quot;13&quot;, &quot;name&quot;: &quot;JR&quot; },
        ///	{ &quot;id&quot;: &quot;14&quot;, &quot;name&quot;: &quot;MD&quot; },
        ///	{ &quot;id&quot;: &quot;15&quot;, &quot;name&quot;: &quot;OP&quot; },
        ///	{ &quot;id&quot;: &quot;16&quot;, &quot;name&quot;: &quot;PHD&quot; },
        ///	{ &quot;id&quot;: &quot;17&quot;, &quot;name&quot;: &quot;SR&quot; },
        ///	{ &quot;id&quot;: &quot;18&quot;, &quot;name&quot;: &quot;V&quot; }
        ///]
        ///.
        /// </summary>
        public static string NameSuffix {
            get {
                return ResourceManager.GetString("NameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{ &quot;id&quot;: &quot;1&quot;, &quot;name&quot;: &quot;None (Unemployed)&quot; },
        ///	{ &quot;id&quot;: &quot;2&quot;, &quot;name&quot;: &quot;Account Executive&quot; },
        ///	{ &quot;id&quot;: &quot;3&quot;, &quot;name&quot;: &quot;Accountant&quot; },
        ///	{ &quot;id&quot;: &quot;4&quot;, &quot;name&quot;: &quot;Acrobat&quot; },
        ///	{ &quot;id&quot;: &quot;5&quot;, &quot;name&quot;: &quot;Actor/Actress, Not Doing Stunts&quot; },
        ///	{ &quot;id&quot;: &quot;6&quot;, &quot;name&quot;: &quot;Actuary&quot; },
        ///	{ &quot;id&quot;: &quot;7&quot;, &quot;name&quot;: &quot;Administrator&quot; },
        ///	{ &quot;id&quot;: &quot;8&quot;, &quot;name&quot;: &quot;AFP COMM OFFICER (2nd Lt Up)&quot; },
        ///	{ &quot;id&quot;: &quot;9&quot;, &quot;name&quot;: &quot;AFP Non-Comm Officer (Enlisted Men)&quot; },
        ///	{ &quot;id&quot;: &quot;10&quot;, &quot;name&quot;: &quot;Agent, Insurance&quot; },
        ///	{ &quot;id&quot;: &quot;11&quot;, &quot;name&quot;: &quot;Agent, Narcot [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{ &quot;id&quot;: &quot;1&quot;, &quot;name&quot;: &quot;REFERRAL OF INSULAR LIFE ADVISOR/ AGENT&quot; },
        ///	{ &quot;id&quot;: &quot;9&quot;, &quot;name&quot;: &quot;REFERRAL FROM UNIONBANK BRANCH&quot; },
        ///	{ &quot;id&quot;: &quot;10&quot;, &quot;name&quot;: &quot;REFERRAL FROM AN INLIFE AFFILIATE&quot;},
        ///	{ &quot;id&quot;: &quot;2&quot;, &quot;name&quot;: &quot;SOCIAL MEDIA, FACEBOOK/ INSTAGRAM/ TWITTER&quot; },
        ///	{ &quot;id&quot;: &quot;3&quot;, &quot;name&quot;: &quot;REFERRAL OF FAMILY/ FRIENDS/ RELATIVES&quot; },
        ///	{ &quot;id&quot;: &quot;4&quot;, &quot;name&quot;: &quot;ONLINE ADS&quot; },
        ///	{ &quot;id&quot;: &quot;5&quot;, &quot;name&quot;: &quot;INTERNET/ GOOGLE SEARCH&quot; },
        ///	{ &quot;id&quot;: &quot;6&quot;, &quot;name&quot;: &quot;BLOG&quot; },
        ///	{ &quot;id&quot;: &quot;7&quot;, &quot;name&quot;: &quot;EMAIL&quot; },
        ///	{ &quot;id&quot;: &quot;8&quot;, &quot;name&quot;: &quot;N [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReferralSource {
            get {
                return ResourceManager.GetString("ReferralSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;id&quot;: &quot;1&quot;,
        ///		&quot;Region&quot;: &quot;ABRA&quot;,
        ///		&quot;City&quot;:
        ///		[
        ///			{ &quot;id&quot;: &quot;1&quot;, &quot;name&quot;: &quot;Bangued&quot; },
        ///			{ &quot;id&quot;: &quot;2&quot;, &quot;name&quot;: &quot;Boliney&quot; },
        ///			{ &quot;id&quot;: &quot;3&quot;, &quot;name&quot;: &quot;Bucay&quot; },
        ///			{ &quot;id&quot;: &quot;4&quot;, &quot;name&quot;: &quot;Bucloc&quot; },
        ///			{ &quot;id&quot;: &quot;5&quot;, &quot;name&quot;: &quot;Daguioman&quot; },
        ///			{ &quot;id&quot;: &quot;6&quot;, &quot;name&quot;: &quot;Danglas&quot; },
        ///			{ &quot;id&quot;: &quot;7&quot;, &quot;name&quot;: &quot;Dolores&quot; },
        ///			{ &quot;id&quot;: &quot;8&quot;, &quot;name&quot;: &quot;La Paz&quot; },
        ///			{ &quot;id&quot;: &quot;9&quot;, &quot;name&quot;: &quot;Lacub&quot; },
        ///			{ &quot;id&quot;: &quot;10&quot;, &quot;name&quot;: &quot;Lagangilang&quot; },
        ///			{ &quot;id&quot;: &quot;11&quot;, &quot;name&quot;: &quot;Lagayan&quot; },
        ///			{ &quot;id&quot;: &quot;12&quot;, &quot;name&quot;....
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
    }
}
