export const RelationshipOwner =
[
	{ id: "1",  name: "AUNT" },
	{ id: "2",  name: "BROTHER" },
	{ id: "3",  name: "BUSINESS PARTNER" },
	{ id: "4",  name: "COMMON-LAW SPOUSE" },
	{ id: "5",  name: "COMPANY" },
	{ id: "6",  name: "DAUGHTER" },
	{ id: "7",  name: "DEPENDENT" },
	{ id: "8",  name: "EMPLOYEE" },
	{ id: "9",  name: "EMPLOYER (KEY MAN)" },
	{ id: "10", name: "ESTATE" },
	{ id: "11", name: "FATHER" },
	{ id: "12", name: "FIANCEE" },
	{ id: "13", name: "FOSTER PARENT" },
	{ id: "14", name: "FRIEND" },
	{ id: "15", name: "GRANDDAUGHTER" },
	{ id: "16", name: "GRANDFATHER" },
	{ id: "17", name: "GRANDMOTHER" },
	{ id: "18", name: "GRANDSON" },
	{ id: "19", name: "GUARDIAN/CUSTODIAN" },
	{ id: "20", name: "MOTHER" },
	{ id: "21", name: "NEPHEW" },
	{ id: "22", name: "NIECE" },
	{ id: "23", name: "OTHERS" },
	{ id: "24", name: "SAME PERSON" },
	{ id: "25", name: "SISTER" },
	{ id: "26", name: "SON" },
	{ id: "27", name: "SPOUSE" },
	{ id: "28", name: "UNCLE" }
];
