export enum StorageType {
    //GROUP
    ACCESS_DATA = 'ACCESS',
    SESSION = 'SESSION',
    POST_GROUP_QUOTE = 'QUOTE_FORM',
    GROUP_PLAN_DATA = 'GROUP_PLAN_DATA',
    REQUIREMENTS_DATA  = 'REQUIREMENTS_DATA',
    STUDENTS_TEACHERS_BENEFITS = 'STUDENTS_TEACHERS_BENEFITS',

    //PS LITE
    QUOTE_EXTERNAL_DATA = 'QUOTE_EXTERNAL_DATA',
    QUOTE_INTERNAL_DATA = 'QUOTE_INTERNAL_DATA',
    APPLY_DATA = 'APPLY_DATA',

    //PRIME CARE
    QUOTE_PC_DATA = 'QUOTE_PC_DATA',
    APPLY_PC_DATA = 'APPLY_PC_DATA',

    //GENERIC
    POLICYNO = 'POLICYNO'
  }
  
  export enum WebStorageType {
    LOCAL = 1,
    SESSION = 2,
    COOKIE = 3
  }