CREATE TABLE [dbo].[InsuranceApplications] (
    [ClusteringId]            BIGINT             IDENTITY (1, 1) NOT NULL,
    [Id]                      UNIQUEIDENTIFIER   NOT NULL,
    [DateCreated]             DATETIMEOFFSET (7) CONSTRAINT [DF_InsuranceApplications_DateCreated] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [PlanCode]                VARCHAR (20)       NOT NULL,
    [PlanName]                NVARCHAR (30)      NOT NULL,
    [PlanPaymentMode]         VARCHAR (20)       NOT NULL,
    [PlanFaceAmount]          DECIMAL (19, 4)    NOT NULL,
    [PlanPremium]             DECIMAL (19, 4)    NOT NULL,
    [AgentFirstName]          NVARCHAR (50)      NULL,
    [AgentLastName]           NVARCHAR (50)      NULL,
    [ReferralSource]          NVARCHAR (50)      NULL,
    [Heallth1]                VARCHAR (10)       NULL,
    [Heallth2]                VARCHAR (10)       NULL,
    [Heallth3]                VARCHAR (10)       NULL,
    [Fatca1]                  VARCHAR (10)       NULL,
    [Fatca2]                  VARCHAR (10)       NULL,
    [Question1]               VARCHAR (10)       NULL,
    [Question2]               VARCHAR (10)       NULL,
    [PolicyDeliveryOption]    VARCHAR (20)       NULL,
    [OwnerId]                 UNIQUEIDENTIFIER   NOT NULL,
    [InsuredId]               UNIQUEIDENTIFIER   NOT NULL,
    [InsuredRelationship]     VARCHAR (20)       NULL,
    [BeneficiaryId]           UNIQUEIDENTIFIER   NOT NULL,
    [BeneficiaryRelationship] VARCHAR (20)       NULL,
    [BeneficiaryRight]        VARCHAR (20)       NULL,
    [BeneficiaryPriority]     VARCHAR (20)       NULL,
    CONSTRAINT [PK_InsuranceApplications] PRIMARY KEY NONCLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InsuranceApplications_InsuranceApplications] FOREIGN KEY ([Id]) REFERENCES [dbo].[InsuranceApplications] ([Id]),
    CONSTRAINT [FK_InsuranceApplications_Persons_Beneficiary] FOREIGN KEY ([BeneficiaryId]) REFERENCES [dbo].[Persons] ([Id]),
    CONSTRAINT [FK_InsuranceApplications_Persons_Insured] FOREIGN KEY ([InsuredId]) REFERENCES [dbo].[Persons] ([Id]),
    CONSTRAINT [FK_InsuranceApplications_Persons_Owner] FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[Persons] ([Id])
);

